spring:
  application:
    name: photodiary-backend
  profiles:
    group:
      local: local-db
    active: local

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 4MB

  datasource:
    url: jdbc:mysql://photodiary.chiciye68pa4.ap-northeast-2.rds.amazonaws.com:3306/photodiary
    username: devuser
    password: photopass123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

cloud:
  aws:
    s3:
      bucket: photodiary-image-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

kakao:
  api:
    key: 66a9a980e11125a18339f31fd49fc39c
