spring:
  application:
    name: photodiary-backend
  profiles:
    group:
      local: local-db
    active: local

  # 업로드 가능 용량 증대
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 4MB

kakao:
  api:
    key: ${KAKAO_API_KEY}

---
# 로컬 DB
spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.H2Dialect
